apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-backend
  labels:
    app: {{ .Values.app.name }}-backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.app.name }}-backend
