apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-frontend
  labels:
    app: {{ .Values.app.name }}-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.app.name }}-frontend
